apiVersion: 1
policies:
  - orgId: 1
    receiver: default-email
    group_by: [alertname]
    group_wait: 30s
    group_interval: 2m
    repeat_interval: 4h
    routes:
      - receiver: slack-devops
        object_matchers:
          - ["severity", "=", "high"]
