server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Linux syslog-like files
  - job_name: syslog
    static_configs:
      - targets: [localhost]
        labels:
          job: syslog
          host: ${HOSTNAME}
          __path__: /var/log/*.log
    pipeline_stages:
      - multiline:
          firstline: '^\w{3}\s+\d{1,2}\s\d{2}:\d{2}:\d{2}'
      - match:
          selector: '{job="syslog"}'
          stages:
            - regex:
                expression: '^(?P<ts>\w{3}\s+\d{1,2}\s\d{2}:\d{2}:\d{2}) (?P<host>\S+) (?P<proc>[^:]+): (?P<msg>.*)'
            - labels:
                proc:
            - output:
                source: msg

  # Docker JSON logs (any container on the same host)
  - job_name: docker
    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339
      - output:
          source: log
    static_configs:
      - targets: [localhost]
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log

  # Example: your app writing JSON to a file
  - job_name: app_json
    static_configs:
      - targets: [localhost]
        labels:
          job: app
          service: my-dotnet-api
          env: dev
          __path__: /var/log/myapp/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: message
            svc: svc
            user: user
            path: path
            status: status
            elapsedMs: elapsedMs
      - labels:
          level:
          svc:
          status:
      - output:
          source: msg

  - job_name: dev_app_json
    static_configs:
      - targets: [localhost]
        labels:
          job: app
          service: my-dotnet-api
          env: dev
          __path__: /logs/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: message
            svc: svc
            time: time
      - labels:
          level:
          svc:
      - output:
          source: msg
